### ISSUE TITLE
Fatal error: require(): ../vendor/autoload.php

### ISSUE THREAD

**Issue by iltis42** [vijayhardaha/wc-pdf-invoices-bulk-download#1]
Dear Vijay, 
i want kindly ask for your support. I have tried to upload your plugin to my recent WordPress 5.8.2, by selecting ZIP download from github code button, pluging loaded and installed correctly. Hence activating it, there is some fatal error as below. I have attached below the zip file i got from master branch. 
My question if your plugin is compatible with above WP version, and if you have an idea what i am doing wrong. Any option to get behind this ?
Thanks in advance for your answer!

[wc-pdf-invoice-bulk-download-master.zip](https://github.com/vijayhardaha/wc-pdf-invoice-bulk-download/files/7562649/wc-pdf-invoice-bulk-download-master.zip)

line 196 Fatal error: require(): Failed opening required '/mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoice-bulk-download-master/vendor/autoload.php' (include_path='.:/opt/RZphp73/includes') in /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoice-bulk-download-master/includes/class-wc-pdf-invoices-bulk-download.php on line 196

**Comment by vijayhardaha** [comment]
Hey,

Thanks for letting me know about the error. I have fixed the error. you can download the latest [zip](https://github.com/vijayhardaha/wc-pdf-invoice-bulk-download/releases) and try it.

Thanks.

**Comment by iltis42** [comment]
Thanks for the quick fix, plugin now got installed and activated, and yes i see another issue :), no matter the time span i configure for download, i see below Stack trace (2) in php class-wc-pdf-invoices-bulk-download-async-request.php line 175, and an info box (1) pop's up. 
Except asking my provider for more resorces (what may be an issue with strato ;), do you see a way for and improvement in terms of resources ?

1)
"Internal Server Error. Please, increase your System Status Limits (PHP Time Limit, PHP Memory Limit, PHP Max Input Vars) or contact with your hosting.".

2)
2021-11-18T14:58:53+00:00 CRITICAL Uncaught Error: Call to undefined method WC_PDF_Invoices_Bulk_Download_Async_Request::woocommerce_pdf_invoices_plugin() in /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoices-bulk-download/includes/admin/class-wc-pdf-invoices-bulk-download-async-request.php:175
Stack trace:
#0 /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoices-bulk-download/includes/admin/class-wc-pdf-invoices-bulk-download-async-request.php(102): WC_PDF_Invoices_Bulk_Download_Async_Request->run(Array)
#1 /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoices-bulk-download/includes/admin/class-wc-pdf-invoices-bulk-download-async-request.php(71): WC_PDF_Invoices_Bulk_Download_Async_Request->generate_zip(Array)
#2 /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoices-bulk-download/vendor/deliciousbrains/wp-background-processing/classes/wp-async-request.php(168): WC_PDF_Invoices_Bulk_ in /mnt/web501/d0/41/510633541/htdocs/WordPress_SecureMode_01/wp-content/plugins/wc-pdf-invoices-bulk-download/includes/admin/class-wc-pdf-invoices-bulk-download-async-request.php in Zeile 175

**Comment by vijayhardaha** [comment]
I will fix it soon, There is a problem is a plugin. I didn't use it for a very long time. that's why it has some bugs. I will fix all the things and test then update the release.

**Comment by vijayhardaha** [comment]
Please try the latest zip from [v1.0.0](https://github.com/vijayhardaha/wc-pdf-invoice-bulk-download/releases/tag/v1.0.0)

**Comment by iltis42** [comment]
Works, all fine, thanks!
![image](https://user-images.githubusercontent.com/34288016/142477061-94c224fc-b3d6-4a59-971a-d49d8d554e0f.png)

**Comment by vijayhardaha** [comment]
Good to know. I have published a [new release](https://github.com/vijayhardaha/wc-pdf-invoices-bulk-download/releases/tag/v1.0.1) with all the plugin information.
